In [1]:
import torch

In [26]:
torch.manual_seed(1234)
A, B = 2, 6
x = torch.randint(0, 10, (A, B))
w = torch.randint(0, 10, (B, A))

print(x)
print(w)
print(torch.matmul(w, x))
print(w @ x)
print(5*4+3+6*6+5*2+6*8)

tensor([[5, 1, 6, 5, 6, 4],
        [2, 5, 5, 9, 3, 1]])
tensor([[4, 2],
        [3, 2],
        [6, 8],
        [2, 2],
        [8, 2],
        [0, 4]])
tensor([[ 24,  14,  34,  38,  30,  18],
        [ 19,  13,  28,  33,  24,  14],
        [ 46,  46,  76, 102,  60,  32],
        [ 14,  12,  22,  28,  18,  10],
        [ 44,  18,  58,  58,  54,  34],
        [  8,  20,  20,  36,  12,   4]])
tensor([[ 24,  14,  34,  38,  30,  18],
        [ 19,  13,  28,  33,  24,  14],
        [ 46,  46,  76, 102,  60,  32],
        [ 14,  12,  22,  28,  18,  10],
        [ 44,  18,  58,  58,  54,  34],
        [  8,  20,  20,  36,  12,   4]])
117
